# Generated by Django 5.2.1 on 2025-06-05 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_expense_income'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
