# Generated by Django 5.2.1 on 2025-06-05 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_transaction_delete_expense_delete_income'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
