# Generated by Django 5.2.1 on 2025-06-10 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='total',
        ),
    ]
