# Generated by Django 5.0.9 on 2025-06-13 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0008_category_user_hiddencategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.DeleteModel(
            name='HiddenCategory',
        ),
    ]
